//! Framework-owned reference mechanisms: the skill analogue of the
//! warehouse `leg_demo`. These prove the pipeline before any model
//! author is in the loop. The baseline *of a pack* lives in the pack;
//! this module only carries the pipeline-validation helpers.

use anyhow::Result;

use crate::experiment::{
    Condition, Experiment, InputDrive, OutputSeries, simulated_channel,
};
use crate::lexicon::Lexicon;
use crate::mechanism::MechanismModel;

/// Synthetic observations for fitting-infrastructure validation:
/// curves generated by a known theta, the fit must recover it without
/// ever seeing it.
///
/// Returns experiments at the given input levels (default
/// `0 / 31.6 / 100`, the binding pack's visible grid — pass any other
/// levels for a different pack), driving the lexicon's primary input
/// channel and recording its primary output channel.
pub fn synthetic_experiments(
    model: &dyn MechanismModel,
    true_theta: &[f64],
    inputs: &[f64],
    lexicon: &Lexicon,
) -> Result<Vec<Experiment>, crate::experiment::SimError> {
    let time: Vec<f64> = (0..=100).map(|step| step as f64 * 0.2).collect();

    let input_channel = lexicon.primary_input().name.clone();
    let output_channel = lexicon.primary_output().name.clone();

    let mut experiments = Vec::new();

    for (index, input) in inputs.iter().copied().enumerate() {
        let mut experiment = Experiment {
            subject: format!("synthetic-{index}"),
            condition: Condition::Level(input),
            t: time.clone(),
            inputs: vec![InputDrive::constant(&input_channel, input)],
            outputs: vec![OutputSeries {
                channel: output_channel.clone(),
                y: Vec::new(),
            }],
        };

        let simulated = model.simulate(true_theta, &experiment)?;

        let y = simulated_channel(&simulated, &output_channel)
            .ok_or_else(|| {
                crate::experiment::SimError::Invalid(format!(
                    "mechanism does not output `{output_channel}`",
                ))
            })?
            .to_vec();

        experiment.outputs[0].y = y;

        experiments.push(experiment);
    }

    Ok(experiments)
}